pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn package'
            }
        }
        stage('Deliver') {
            steps {
                bat './jenkins/scripts/deliver.sh'
            }
        }
    }
}
