pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'C:/Users/ShriramSubramanian/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven/apache-maven-3.5.4/bin/mvn package'
            }
        }
        stage('Deliver') {
            steps {
                bat './jenkins/scripts/deliver.sh'
            }
        }
    }
}
